### ISSUE TITLE
服务端发现connect reset的情况

### ISSUE THREAD

**Issue by alohaking** [coding4m/fastdfs-client#5]
服务端报错如下
```
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
  ...
```

这个客户端应该没有关闭channel的操作，为什么会出现这种现象

**Comment by coding4m** [comment]
有更完整的异常信息吗？
